name: 🐛 Bug Report
description: Found a bug? Help us fix it!
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: 🐛 What went wrong?
      description: Describe the bug in simple terms
      placeholder: "The login button doesn't work when I..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🔄 How to reproduce it?
      description: Step-by-step instructions
      placeholder: |
        1. Open the app
        2. Tap on login
        3. Enter email and password
        4. Tap login button
        5. Nothing happens
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ What should have happened?
      description: What did you expect to happen instead?
      placeholder: "I should have been logged in and taken to the home screen"
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: 📱 Device info
      description: What device/Android version?
      placeholder: "Samsung Galaxy S21, Android 13"