name: ✨ Feature Request
description: Got an idea? Let's build it!
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: ✨ What feature do you want?
      description: Describe the feature you'd like to see
      placeholder: "I want to be able to download podcasts for offline listening"
    validations:
      required: true

  - type: textarea
    id: why-needed
    attributes:
      label: 🤔 Why do you need this?
      description: What problem does this solve?
      placeholder: "Users want to listen to podcasts without internet connection"
    validations:
      required: true

  - type: textarea
    id: user-story
    attributes:
      label: 👤 User Story
      description: Describe how a user would use this feature
      placeholder: "As a user, I want to download episodes so I can listen offline during commute"

  - type: input
    id: figma
    attributes:
      label: 🎨 Figma Design (if available)
      description: Link to Figma design
      placeholder: "https://figma.com/file/..."